# Generated by Django 5.2.16 on 2026-07-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0022_bookshelf_percent'),
        ('sopds_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosyncprogress',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opds_catalog.book'),
        ),
        migrations.CreateModel(
            name='BookDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=32, unique=True)),
                ('method', models.CharField(choices=[('filename', 'File name md5'), ('binary', 'Partial content md5')], max_length=16)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='opds_catalog.book')),
            ],
        ),
    ]
