# Generated by Django 5.2.16 on 2026-07-28 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0028_collection_collectionbook_collection_books_and_more'),
        ('sopds_sync', '0002_kosyncprogress_book_bookdigest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonReaderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=512)),
                ('marker', models.CharField(max_length=64)),
                ('rule', models.CharField(blank=True, default='', max_length=16)),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opds_catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'path')},
            },
        ),
    ]
