# Generated by Django 5.2.16 on 2026-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0017_scanseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='search_full_name',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='search_title',
            field=models.CharField(db_index=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='series',
            name='search_ser',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
