# Generated by Django 5.2.16 on 2026-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0018_search_fields_default_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
