# Generated by Django 5.2.16 on 2026-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0020_book_book_registerdate_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='enriched',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
