# Generated by Django 5.2.16 on 2026-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0021_book_enriched_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='percent',
            field=models.FloatField(default=None, null=True),
        ),
    ]
