# Generated by Django 5.2.16 on 2026-07-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0022_bookshelf_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStat',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stat', serialize=False, to='opds_catalog.book')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('reads', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(models.OrderBy(models.F('downloads'), descending=True), name='bookstat_downloads_desc')],
            },
        ),
    ]
