# Generated by Django 5.2.16 on 2026-07-26 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0023_bookstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Finished'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('books_added', models.IntegerField(default=0)),
                ('books_deleted', models.IntegerField(default=0)),
                ('books_skipped', models.IntegerField(default=0)),
                ('bad_books', models.IntegerField(default=0)),
                ('books_in_archives', models.IntegerField(default=0)),
                ('arch_scanned', models.IntegerField(default=0)),
                ('arch_skipped', models.IntegerField(default=0)),
                ('bad_archives', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
