# Generated by Django 5.2.16 on 2026-07-26 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0024_scanrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookshelf',
            index=models.Index(fields=['rating', 'book'], name='bookshelf_rating_book'),
        ),
    ]
