# Generated by Django 5.2.16 on 2026-07-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0025_bookshelf_bookshelf_rating_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='device_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
