# Generated by Django 5.2.16 on 2026-07-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0026_theme_device_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('search_name', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['search_name'],
            },
        ),
        migrations.CreateModel(
            name='btag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.tag')),
            ],
            options={
                'unique_together': {('book', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(through='opds_catalog.btag', to='opds_catalog.tag'),
        ),
    ]
